### ISSUE TITLE
Iframe resource consumption

### ISSUE THREAD

**Issue by davidheyman** [axismaps/evolution-of-risk#34]
We need to look for ways to reduce the resource consumption of the iframe maps to improve performance and reliability. Maybe using more simplified geometries would help and we should look into ways to make sure only 1 iframe map is running at a time. Otherwise, run some profiles to see what's using the most CPU and see if there's a way to get it to run more efficiently.

**Comment by awoodruff** [comment]
Country polygons are more simplified now (helps the % urban map a bit), and it should now also make sure that only one iframe or video is playing at a time. Otherwise I haven't been able to find anything to improve. Nothing notable shows up in profiles in Chrome, although my computer probably just isn't crummy enough. I'm sure some loops and things could be more efficient but as far as I can tell it's simply the frequent rendering that's costly.
