### ISSUE TITLE
Jump people back to their place in the text

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/evolution-of-risk#58]
What do you think about jumping people back to their place in the text after they are sent down to the reference list (maybe a small up arrow beside the citation)? Is this an unnecessary enhancement or something that will prevent a lot of frustration?

**Comment by kingfisher13** [comment]
@bcsheesley This is what it looks like:

![image](https://cloud.githubusercontent.com/assets/9831929/12127573/a1369a26-b3bd-11e5-808b-23be03a278b5.png)

**Comment by bcsheesley** [comment]
Nice! That looks great.

On Tue, Jan 5, 2016 at 3:04 PM, Josh notifications@github.com wrote:

> This is what it looks like:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/9831929/12127573/a1369a26-b3bd-11e5-808b-23be03a278b5.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/axismaps/evolution-of-risk/issues/58#issuecomment-169133612
> .

## 

---

Ben Sheesley
ben@axismaps.com
(254) 722-8014

Axis Maps LLC

## http://www.axismaps.com

**Comment by davidheyman** [comment]
@kingfisher13 This is a great idea. Three quick requests:
1. Instead of jumping back to the top offset of the footnote reference, can you store the scrollTop of the page when the user clicks and jump back to that? I think that would be less disorienting.
2. Can you add about 10px extra scroll to the footnote? I'm finding those a little close to the top of the page.
3. Unless they're going to hurt performance, can you use css transitions on that background effect? I think it would look good to fade in quickly (250ms maybe?) and then fade out slower.

**Comment by kingfisher13** [comment]
eb0a6a2dd4fcb015f9cb5a8beaee328f6d1bf966 fixes this
